name: Test SOCKS5 Proxies

on:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_proxies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      
    - name: Install dependencies
      run: |
        pip install requests pysocks

    - name: Run proxy test
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN}}
        PROXY_DATA: ${{ secrets.PROXY_DATA }}
      run: |
        python test.py